version: '3.7'

services:
  sports-backend:
    image: asia.gcr.io/toge-382108/sports-backend:3.8
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    volumes:
      - ./src:/myfolder/src
    ports:
      - 3000:3000

  # sports-database:
  #   image: mysql:latest
  #   environment:
  #     MYSQL_DATABASE: 'sports'
  #     MYSQL_ROOT_PASSWORD: '12345678'
  #   ports:
  #     - 3306:3306

  # sports-redis:
  #   image: redis:latest
  #   ports:
  #     - 6379:6379
